eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000


spring:
  application:
    name: olymtech-gateway-admin
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache:  false

security:
  user:
    name: admin
    password: test
