server:
  port: 10092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olymtech-api-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: select 1
  jpa:
    hibernate:
      show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false

flyway:
  clean-on-validation-error: true

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka.olymtech.com:8761/eureka/

logging:
  config: classpath:logbak.xml
  path:   ${HOME}/log
